apiVersion: v1
kind: ServiceAccount
metadata:
  name: poison-detector
  namespace: poison-detector
  labels:
    app: poison-detector
    component: serviceaccount
    version: v1
    app.kubernetes.io/name: poison-detector
    app.kubernetes.io/component: serviceaccount
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/poison-detector-service-role"
automountServiceAccountToken: false
